services:
    _defaults:
      autowire: true

    odiseo_sylius_mercado_pago_plugin.payum_gateway_factory.mercado_pago:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Odiseo\SyliusMercadoPagoPlugin\Payum\MercadoPagoGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: mercado_pago }

    odiseo_sylius_mercado_pago_plugin.payum_action.mercado_pago.capture:
        class: Odiseo\SyliusMercadoPagoPlugin\Payum\Action\CaptureAction
        public: true
        arguments:
            - '@liip_imagine.cache.manager'
        tags:
            - { name: payum.action, factory: mercado_pago, alias: payum.action.capture }

    odiseo_sylius_mercado_pago_plugin.payum_action.mercado_pago.notify:
        class: Odiseo\SyliusMercadoPagoPlugin\Payum\Action\NotifyAction
        public: true
        tags:
            - { name: payum.action, factory: mercado_pago, alias: payum.action.notify }
